title: YAML Title
author: bhitney
email: bhitney@microsoft.com
description: > # this means to ignore newlines until "baseurl:"
  YAML Description

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima

collections_dir: plans

collections:
  modern_workplace  :
    output          : true
    permalink       : /:collection/:path/
  business_applications :
    output          : true
    permalink       : /:collection/:path/
  azure  :
    output          : true
    permalink       : /:collection/:path/
  
